# Generated by Django 4.1.7 on 2023-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_orders_products_alter_orders_quantities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='Color', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='companyName',
            field=models.CharField(default='Company name', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(default='Product name', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='refurbished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='screen',
            field=models.CharField(default='Screen', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default='Size', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
