# Generated by Django 4.1.7 on 2023-04-07 18:21

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_carts_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='img',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='product',
        ),
        migrations.AddField(
            model_name='carts',
            name='products',
            field=models.ManyToManyField(related_name='carts', to='cart.products'),
        ),
        migrations.AddField(
            model_name='carts',
            name='quantities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='carts',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
