# Generated by Django 4.1.7 on 2023-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_remove_carts_quantities_alter_carts_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='total_price',
        ),
    ]
