# Generated by Django 4.1.7 on 2023-04-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_remove_carts_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
    ]
